root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

gitbook:
  spaceID: FTk8pBcGEQwB11SlngkL

github:
  sync:
    direction: gitbook-to-github
  pull:
    automatic: true
    features: true
