name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install HonKit and plugins
        run: |
          npm install -g honkit
          chmod +x ./scripts/install-honkit-plugins.sh
          ./scripts/install-honkit-plugins.sh
          
      - name: Build documentation
        run: |
          honkit build
          
      - name: Upload documentation build
        uses: actions/upload-artifact@v4
        with:
          name: documentation-build
          path: _book
          retention-days: 1
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download documentation build
        uses: actions/download-artifact@v4
        with:
          name: documentation-build
          path: _book
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book