name: Sync to GitBook

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook install
          
      - name: Build GitBook
        run: gitbook build
        
      - name: Deploy to GitBook
        env:
          GITBOOK_TOKEN: ${{ secrets.GITBOOK_TOKEN }}
        run: |
          # You'll need to set up your token as a GitHub secret
          # This is a simplified example - actual implementation depends on GitBook's API
          curl -X POST \
            -H "Authorization: Bearer $GITBOOK_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"branch":"main","message":"Auto-sync from GitHub"}' \
            https://api.gitbook.com/v1/spaces/YOUR_SPACE_ID/sync